dataset: TsinghuaC3I/MedXpertQA

provider: vllm # [vllm, openai, ollama]

base_url: http://192.168.11.80:8000/v1  # vLLM endpoints
# base_url: null  # null for official OpenAI API

model: qwen3-235b-a22b-thinking  # vLLM model
max_completion_tokens: 38000
reasoning: true
temperature: 0.0
num_workers: 48

max_samples: 2500       # Process first N questions
#question_range: [0, 10]  # Process questions from index 0 to 10 (uncomment to use)

judge: o3-mini-2025-01-31

prompt_profile: zero_shot_cot_mc
boxed_final: false
prompts:
  zero_shot_cot_mc: |
    You are an experienced medical doctor. Think step by step before deciding the single best answer.
    After reasoning, output exactly the following three lines:
    Explanation: <concise medical reasoning>
    Answer: <one of A, B, C, D, E, F, G, H, I, J>
    Confidence: <0-100%>
